baseURL = "https://gourmetpratico.com.br"
languageCode = "pt-br"
title = "Gourmet Prático | ChefBrico"

[params]
    slogan = "Gourmet Prático é uma culinária saudável, sem desperdício de Tempo e Ingredientes na sua Cozinha!"
    author = "Maria Conceição"
    premio = "Vencedora do Prêmio Sebrae Mulher de Negócios"
    whatsapp = "5561996659880"
    preco_kit = 132.00
    cnpj = "36.014.833/0001-59"
